var parameters = {
  "dbs": "_all_dbs",
  "updates": "_db_updates",
  "replicate": "_replicate",
  "docs": "_all_docs",
  "bulk": "_bulk_docs",
  "tasks": "_active_tasks",
  "log": "_log",
  "config": "_config",
  "stats": "_stats",
  "uuids": "_uuids",
  "restart": "_restart",
  "session": "_session",
  "commit": "_ensure_full_commit",
  "changes": "_changes",
  "compact": "_compact",
  "purge": "_purge",
  "cleanup": "_view_cleanup",
  "diff": "_revs_diff",
  "limit": "_revs_limit",
  "security": "_security",
  "temp": "_temp_view",
  "missing": "_missing_revs",
  "design": "_design",
  "view": "_view",
  "show": "_show",
  "list": "_list",
  "info": "_info",
  "update": "_update",
  "rewrite": "_rewrite",
  "local": "_local",
}

module.exports = parameters;
